types:
  - build
  - test

build-docker:
  type: build
  script:
    - docker build -t docker.dolansoft.org/lorenz/dockpipe:$CI_BUILD_REF .
    - docker push docker.dolansoft.org/lorenz/dockpipe:$CI_BUILD_REF
  tags:
    - v2
    - docker
  except:
    - tags

build-tags:
  type: build
  script:
    - docker build -t docker.dolansoft.org/lorenz/dockpipe:$CI_BUILD_REF_NAME .
    - docker push docker.dolansoft.org/lorenz/dockpipe:$CI_BUILD_REF_NAME
  tags:
    - v2
    - docker
  only:
    - tags